### ISSUE TITLE
panic EOF

### ISSUE THREAD

**Issue by spiperac** [radareorg/r2pipe-go#1]
Example source:
package main

import (
    "fmt"
    "r2pipe.go"
)

func main() {
    r2p, err := r2pipe.NewPipe("malloc://256")
    if err != nil {
        panic(err)
    }
    defer r2p.Close()
    _, err = r2p.Cmd("w Hello World")
    if err != nil {
        panic(err)
    }
    buf, err := r2p.Cmd("ps")
    if err != nil {
        panic(err)
    }
    fmt.Println(buf)
}
# Error

panic: EOF

goroutine 16 [running]:
runtime.panic(0x4f34a0, 0xc208000030)
    /usr/lib/go/src/pkg/runtime/panic.c:279 +0xf5
main.main()
    /home/spiperac/Projects/eaxer/eax.go:11 +0x81

goroutine 19 [finalizer wait]:
runtime.park(0x412e90, 0x5c9038, 0x5c7b29)
    /usr/lib/go/src/pkg/runtime/proc.c:1369 +0x89
runtime.parkunlock(0x5c9038, 0x5c7b29)
    /usr/lib/go/src/pkg/runtime/proc.c:1385 +0x3b
runfinq()
    /usr/lib/go/src/pkg/runtime/mgc0.c:2644 +0xcf
runtime.goexit()
    /usr/lib/go/src/pkg/runtime/proc.c:1445
exit status 2

**Comment by spiperac** [comment]
The problem was in old r2 version ( -q0 flag), this can be closed.

**Comment by radare** [comment]
You can close your own issues
