### ISSUE TITLE
Module declares the name wrong

### ISSUE THREAD

**Issue by TheDuchy** [radareorg/r2pipe-go#11]
Module fails to download via go get as the module name is set to `github.com/radareorg/r2pipe-go` and `github.com/radareorg/r2pipe-go` doesn't exist.

```
go get: github.com/radare/r2pipe-go@v0.2.1: parsing go.mod:
        module declares its path as: github.com/radareorg/r2pipe-go
                but was required as: github.com/radare/r2pipe-go
```

Fix:
change the module name to `github.com/radare/r2pipe-go` or migrate the repository to `github.com/radareorg/r2pipe-go`

**Comment by radare** [comment]
Moved!

**Comment by trufae** [comment]
pls confirm it works well now

**Comment by TheDuchy** [comment]
Works like a charm, sorry for late reply.

**Comment by trufae** [comment]
Happy to read that
