### ISSUE TITLE
Archive repository in favor of radareorg/radare2-r2pipe?

### ISSUE THREAD

**Issue by XVilka** [radareorg/r2pipe-go#2]
Since the one in https://github.com/radareorg/radare2-r2pipe/tree/master/go is more updated and receives more attention.

cc @wargio

**Comment by trufae** [comment]
This repo is the one used by Go, you can't reference radare2-r2pipe/go from Go, it needs to be a root repository. so every commit there must be pushed here or make it a submodule from there or something

**Comment by wargio** [comment]
> This repo is the one used by Go, you can't reference radare2-r2pipe/go from Go, it needs to be a root repository. so every commit there must be pushed here or make it a submodule from there or something

tbh, i had to rewrite the go one because it was not working last time i tried to use it.

**Comment by wargio** [comment]
yes, @trufae is correct in his statement.

**Comment by XVilka** [comment]
Ok, no problem then.

**Comment by trufae** [comment]
Its a problem because both codebases should be in sync
