### ISSUE TITLE
Documentation not viewable on pkg.go.dev due to missing license.

### ISSUE THREAD

**Issue by HanEmile** [radareorg/r2pipe-go#3]
Hi there, just wanted to mention that the documentation at [godoc.org](https://godoc.org) will redirect to [pkg.go.dev](https://pkg.go.dev) soon. This is an issue, as [pkg.go.dev](https://pkg.go.dev) currently doesn't display the documentation "due to license restrictions". 

Fix: add some kind of License to this repo.

[https://godoc.org/github.com/radare/r2pipe-go](https://godoc.org/github.com/radare/r2pipe-go)
![image](https://user-images.githubusercontent.com/22756350/104819062-71bd4700-582b-11eb-8dbd-f6d466b84186.png)

[https://pkg.go.dev/github.com/radare/r2pipe-go](https://pkg.go.dev/github.com/radare/r2pipe-go)
![image](https://user-images.githubusercontent.com/22756350/104819226-628ac900-582c-11eb-9594-334f57e042b0.png)

**Comment by trufae** [comment]
Thanks for reporting that. ill take care of that when i have some spare time(R)

**Comment by trufae** [comment]
I've added the MIT license, and also tagged the last commit, but the sites doesn't seems to reflect this (yet). So i assume there's some kind of cache and we need to wait until this gets updated. Or maybe i missed something :?

**Comment by trufae** [comment]
Finally! Seems like moving the repo and importing it back solved the problem

https://pkg.go.dev/github.com/radareorg/r2pipe-go
